### ISSUE TITLE
Change element to bind event listener on

### ISSUE THREAD

**Issue by Anahkiasen** [devjmetivier/gatsby-plugin-page-progress#73]
My page's layout has parts that are full-height and one `<main>` container that is scrollable. But because the package's event listener is bound on `window` the package doesn't work because the window itself doesn't scroll, a particular DOM element does. I tried to bind the event listener to that element in particular and it fixes the event not firing, but the formula to get the progress would need to be amended to use `scrollHeight`/`scrollTop` too.

**Describe the solution you'd like**
Ideally I think it could be as simple as adding an option for this, which would default to the `window` element if not provided.

```js
{
    resolve: "gatsby-plugin-page-progress",
    options: {
        scrollingElement: '.some-selector',
    }
}
```

**Comment by devjmetivier** [comment]
@Anahkiasen Hello 👋

That's an interesting use case. It sounds like you've attempted some work in your fork already. Would you be interested in submitting a pull request?

I have some other things that I'm working on at the moment but I can totally see the value in this enhancement. It might take me a week or two for me otherwise.

### Suggestion

Instead of `scrollingElement`, could we do this naming scheme?

```js
{
    resolve: "gatsby-plugin-page-progress",
    options: {
        bindTo: '.this',
    }
}
```

"Bind to" sounds like a more "actionable" setting in my opinion. Let me know your thoughts!

**Comment by Anahkiasen** [comment]
Yeah `scrollingElement` was an example but `bindTo` works for me. I ended up making custom logic in my `gatsby-browser` which was a lot simpler because I had reduced needs:

```js
export const onRouteUpdate = ({ location }) => {
    if (!location.pathname.match(/(blogposts|stories)\/./)) {
        return;
    }

    let scrolling = false;
    const scrollingElement = document.querySelector("main > div");
    const progressBarElement = document.querySelector("#progress");

    scrollingElement.addEventListener("scroll", () => {
        const progress = (scrollingElement.scrollTop / scrollingElement.scrollHeight) * 100;

        if (!scrolling) {
            window.requestAnimationFrame(() => {
                progressBarElement.setAttribute("style", `width: ${progress}%;`);
                scrolling = false;
            });

            scrolling = true;
        }
    });
};
```

To make it work in the plugin you need way more logic to account for browser compatibility and so on, will try to take a look but not promising anything :/
