### ISSUE TITLE
Progress Bar to render below Fixed Header

### ISSUE THREAD

**Issue by greatgumz** [devjmetivier/gatsby-plugin-page-progress#76]
**Is your feature request related to a problem? Please describe.**
I want to be able to add an optional parameter to display the progress bar below the fixed header

**Describe the solution you'd like**
If the user has a fixed header, they should be given the option to define the starting headerHeight just like the footerHeight as a fixed position to offset the scroll calcuations

**Describe alternatives you've considered**

**Additional context**

**Comment by devjmetivier** [comment]
@greatgumz #77 has been merged. Looks great.

v2.2.0 published with your changes:

https://unpkg.com/browse/gatsby-plugin-page-progress@2.2.0/

Thanks for your contribution!
